# Generated by Django 3.0.7 on 2020-06-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('project_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Проекты',
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'ordering': ['user_name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('task_name', models.TextField()),
                ('executor_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offershub_asana_api.User')),
                ('project_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offershub_asana_api.Project')),
            ],
            options={
                'verbose_name_plural': 'Задания',
                'ordering': ['task_name'],
            },
        ),
    ]
